type JongersType = {
  photo?: string;
  name: string;
  nickname: string;
  gender: 'Men' | 'Women';
  division?: string;
  status?: string;
  position: string;
  instagram?: string;
  tiktok?: string;
  linkedin?: string;
};

type ListJongersType = {
  id: number;
  photo?: string;
  name: string;
  nickname: string;
  gender: 'Men' | 'Women';
  division?: string;
  status?: string;
  position: string;
  instagram?: string;
  tiktok?: string;
  linkedin?: string;
};

export const jongers: JongersType[] = [
  {
    photo: '/images/jongers/zadi.webp',
    name: 'Zadi Ahsanul Amal',
    nickname: 'Zadi',
    gender: 'Men',
    division: 'Manager',
    status: '',
    position: 'Manager',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    photo: '/images/jongers/doley.webp',
    name: 'Hanif Abdillah',
    nickname: 'Hanif',
    gender: 'Men',
    division: 'Sekretaris',
    status: '',
    position: 'Sekretaris 1',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    photo: '/images/jongers/ara.webp',
    name: 'Zahra Rahmalia N.',
    nickname: 'Ara',
    gender: 'Women',
    division: 'Sekretaris',
    status: '',
    position: 'Sekretaris 2',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    photo: '/images/jongers/anun.webp',
    name: 'M. Ahsanul Amal',
    nickname: 'Anun',
    gender: 'Men',
    division: 'Bendahara',
    status: '',
    position: 'Bendahara',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    photo: '/images/jongers/bilal.webp',
    name: 'M. Billal Nur Hadi',
    nickname: 'Billal',
    gender: 'Men',
    division: 'Creative',
    status: 'Kadiv',
    position: 'Kadiv Creative',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    photo: '/images/jongers/naya.webp',
    name: 'Inayah Syaffiyah R.',
    nickname: 'Naya',
    gender: 'Women',
    division: 'Creative',
    status: 'Staff',
    position: 'Staff Creative',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    photo: '/images/jongers/roro.webp',
    name: 'Rozanah',
    nickname: 'Roro',
    gender: 'Women',
    division: 'Creative',
    status: 'Staff',
    position: 'Staff Creative',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    photo: '/images/jongers/runi.webp',
    name: 'Khairunnisa Shalmah',
    nickname: 'Runi',
    gender: 'Women',
    division: 'Creative',
    status: 'Staff',
    position: 'Staff Creative',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    photo: '/images/jongers/rifky.webp',
    name: 'Mohammad Rifky',
    nickname: 'Rifki',
    gender: 'Men',
    division: 'Creative',
    status: 'Staff',
    position: 'Staff Creative',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    photo: '/images/jongers/miftah.webp',
    name: 'Miftahul Jannah',
    nickname: 'Miftah',
    gender: 'Women',
    division: 'Creative',
    status: 'Staff',
    position: 'Staff Creative',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    photo: '/images/jongers/shidiq.webp',
    name: 'Azman Shidiq A.',
    nickname: 'Sidiq',
    gender: 'Men',
    division: 'Event',
    status: 'Kadiv',
    position: 'Kadiv Event',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    photo: '/images/jongers/taqi.webp',
    name: 'Taqi Mundzir B.',
    nickname: 'Taqi',
    gender: 'Men',
    division: 'Event',
    status: 'Staff',
    position: 'Staff Event',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    photo: '/images/jongers/ghina.webp',
    name: 'Ghina Asma A. M.',
    nickname: 'Ghina',
    gender: 'Women',
    division: 'Event',
    status: 'Staff',
    position: 'Staff Event',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    photo: '/images/jongers/jikri.webp',
    name: 'Dzikri A.',
    nickname: 'Jikri',
    gender: 'Men',
    division: 'Event',
    status: 'Staff',
    position: 'Staff Event',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    photo: '/images/jongers/ghyffara.webp',
    name: 'Ghyffara Aghaty P.',
    nickname: 'Ghyffara',
    gender: 'Women',
    division: 'Event',
    status: 'Staff',
    position: 'Staff Event',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    photo: '/images/jongers/rina.webp',
    name: 'Nisrina F.',
    nickname: 'Rina',
    gender: 'Women',
    division: 'Event',
    status: 'Staff',
    position: 'Staff Event',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    photo: '/images/jongers/ridho.webp',
    name: 'Ridho Pratama',
    nickname: 'Ridho',
    gender: 'Men',
    division: 'Comdev',
    status: 'Kadiv',
    position: 'Kadiv Comdev',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    photo: '/images/jongers/jaguar.webp',
    name: 'M. Zikri Jaguar.',
    nickname: 'Jaguar',
    gender: 'Men',
    division: 'Event',
    status: 'Staff',
    position: 'Staff Event',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    photo: '/images/jongers/eja.webp',
    name: 'Zahid Faqih A. R.',
    nickname: 'Eja',
    gender: 'Men',
    division: 'Event',
    status: 'Staff',
    position: 'Staff Event',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    photo: '/images/jongers/tao.webp',
    name: 'Tasnim A.',
    nickname: 'Tao',
    gender: 'Women',
    division: '',
    status: 'Member',
    position: 'Member',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    photo: '/images/jongers/ia.webp',
    name: 'Fatihah S.',
    nickname: 'Ia',
    gender: 'Women',
    division: '',
    status: 'Member',
    position: 'Member',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    photo: '/images/jongers/inaya.webp',
    name: 'Putri Inayati.',
    nickname: 'Inaya',
    gender: 'Women',
    division: '',
    status: 'Member',
    position: 'Member',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    photo: '/images/jongers/rahma.webp',
    name: 'Rahma A.',
    nickname: 'Rahma',
    gender: 'Women',
    division: 'Event',
    status: 'Staff',
    position: 'Staff Event',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    photo: '/images/jongers/farah.webp',
    name: 'Farah',
    nickname: 'Farah',
    gender: 'Women',
    division: 'Event',
    status: 'Staff',
    position: 'Staff Event',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    photo: '/images/jongers/jia.webp',
    name: 'Nazria',
    nickname: 'Jia',
    gender: 'Women',
    division: '',
    status: 'Member',
    position: 'Member',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    photo: '/images/jongers/tanti.webp',
    name: 'Octanty M.',
    nickname: 'Tanti',
    gender: 'Women',
    division: '',
    status: 'Member',
    position: 'Member',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    photo: '/images/jongers/khalisa.webp',
    name: 'Khalisa',
    nickname: 'Khalisa',
    gender: 'Women',
    division: '',
    status: 'Member',
    position: 'Member',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    photo: '',
    name: 'Najla K.',
    nickname: 'Najla',
    gender: 'Women',
    division: '',
    status: 'Member',
    position: 'Member',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    photo: '',
    name: 'Najwa Ulya',
    nickname: 'Joel',
    gender: 'Women',
    division: '',
    status: 'Member',
    position: 'Member',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    photo: '',
    name: 'Maysarah',
    nickname: 'Sarah',
    gender: 'Women',
    division: '',
    status: 'Member',
    position: 'Member',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    photo: '',
    name: 'Afaf Hilmi',
    nickname: 'Hilmi',
    gender: 'Men',
    division: '',
    status: 'Member',
    position: 'Member',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
];

export const listJongers: ListJongersType[] = jongers.map((item, index) => ({
  id: index + 1,
  ...item,
}));
