type JongersType = {
  id: number;
  photo?: string;
  name: string;
  nickname: string;
  division?: string;
  status?: string;
  position: string;
  instagram?: string;
  tiktok?: string;
  linkedin?: string;
};

export const listJongers: JongersType[] = [
  {
    id: 1,
    photo: '/images/jongers/zadi.webp',
    name: 'Zadi Ahsanul Amal',
    nickname: 'Zadi',
    division: 'Manager',
    status: '',
    position: 'Manager',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    id: 2,
    photo: '/images/jongers/doley.webp',
    name: 'Hanif Abdillah',
    nickname: 'Hanif',
    division: 'Sekretaris',
    status: '',
    position: 'Sekretaris',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    id: 3,
    photo: '/images/jongers/anun.webp',
    name: 'M. Ahsanul Amal',
    nickname: 'Anun',
    division: 'Bendahara',
    status: '',
    position: 'Bendahara',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    id: 4,
    photo: '/images/jongers/bilal.webp',
    name: 'M. Billal Nur Hadi',
    nickname: 'Billal',
    division: 'Creative',
    status: 'Kadiv',
    position: 'Kadiv Creative',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    id: 5,
    photo: '/images/jongers/naya.webp',
    name: 'Inayah Syaffiyah R.',
    nickname: 'Naya',
    division: 'Creative',
    status: 'Staff',
    position: 'Staff Creative',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    id: 6,
    photo: '/images/jongers/roro.webp',
    name: 'Rozanah',
    nickname: 'Roro',
    division: 'Creative',
    status: 'Staff',
    position: 'Staff Creative',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    id: 7,
    photo: '/images/jongers/runi.webp',
    name: 'Khairunnisa Shalmah',
    nickname: 'Runi',
    division: 'Creative',
    status: 'Staff',
    position: 'Staff Creative',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    id: 8,
    photo: '/images/jongers/rifky.webp',
    name: 'Mohammad Rifky',
    nickname: 'Rifki',
    division: 'Creative',
    status: 'Staff',
    position: 'Staff Creative',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    id: 9,
    photo:
      'https://images.unsplash.com/photo-1633332755192-727a05c4013d?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    name: 'Miftahul Jannah',
    nickname: 'MIftah',
    division: 'Creative',
    status: 'Staff',
    position: 'Staff Creative',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    id: 10,
    photo: '/images/jongers/shidiq.webp',
    name: 'Azman Shidiq A.',
    nickname: 'Sidiq',
    division: 'Event',
    status: 'Kadiv',
    position: 'Kadiv Event',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    id: 11,
    photo:
      'https://images.unsplash.com/photo-1633332755192-727a05c4013d?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    name: 'Taqi Mundzir B.',
    nickname: 'Taqi',
    division: 'Event',
    status: 'Staff',
    position: 'Staff Event',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    id: 12,
    photo: '/images/jongers/ghina.webp',
    name: 'Ghina Asma A. M.',
    nickname: 'Ghina',
    division: 'Event',
    status: 'Staff',
    position: 'Staff Event',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    id: 13,
    photo: '/images/jongers/jikri.webp',
    name: 'Dzikri A.',
    nickname: 'Jikri',
    division: 'Event',
    status: 'Staff',
    position: 'Staff Event',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    id: 14,
    photo: '/images/jongers/ghyffara.webp',
    name: 'Ghyffara Aghaty P.',
    nickname: 'Ghyffara',
    division: 'Event',
    status: 'Staff',
    position: 'Staff Event',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    id: 15,
    photo:
      'https://images.unsplash.com/photo-1633332755192-727a05c4013d?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    name: 'Nisrina F.',
    nickname: 'Rina',
    division: 'Event',
    status: 'Staff',
    position: 'Staff Event',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    id: 16,
    photo:
      'https://images.unsplash.com/photo-1633332755192-727a05c4013d?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    name: 'Najla K.',
    nickname: 'Najla',
    division: 'Event',
    status: 'Staff',
    position: 'Staff Event',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    id: 17,
    photo: '/images/jongers/ridho.webp',
    name: 'Ridho Pratama',
    nickname: 'Ridho',
    division: 'Comdev',
    status: 'Kadiv',
    position: 'Kadiv Comdev',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    id: 18,
    photo: '/images/jongers/jaguar.webp',
    name: 'M. Zikri Jaguar.',
    nickname: 'Jaguar',
    division: 'Comdev',
    status: 'Staff',
    position: 'Staff Comdev',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    id: 19,
    photo: '/images/jongers/eja.webp',
    name: 'Zahid Faqih A. R.',
    nickname: 'Eja',
    division: '',
    status: 'Member',
    position: 'Member',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    id: 20,
    photo: '/images/jongers/tao.webp',
    name: 'Tasnim A.',
    nickname: 'Tao',
    division: '',
    status: 'Member',
    position: 'Member',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    id: 21,
    photo: '/images/jongers/ia.webp',
    name: 'Fatihah S.',
    nickname: 'Ia',
    division: '',
    status: 'Member',
    position: 'Member',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    id: 22,
    photo: '/images/jongers/inaya.webp',
    name: 'Putri Inayati.',
    nickname: 'Inaya',
    division: '',
    status: 'Member',
    position: 'Member',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    id: 23,
    photo: '/images/jongers/rahma.webp',
    name: 'Rahma A.',
    nickname: 'Rahma',
    division: '',
    status: 'Member',
    position: 'Member',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    id: 24,
    photo:
      'https://images.unsplash.com/photo-1633332755192-727a05c4013d?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    name: 'Farah',
    nickname: 'Farah',
    division: '',
    status: 'Member',
    position: 'Member',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    id: 25,
    photo: '/images/jongers/jia.webp',
    name: 'Nazria',
    nickname: 'Jia',
    division: '',
    status: 'Member',
    position: 'Member',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    id: 26,
    photo: '/images/jongers/tanti.webp',
    name: 'Octanty M.',
    nickname: 'Tanti',
    division: '',
    status: 'Member',
    position: 'Member',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
  {
    id: 27,
    photo: '/images/jongers/khalisa.webp',
    name: 'Khalisa',
    nickname: 'Khalisa',
    division: '',
    status: 'Member',
    position: 'Member',
    instagram: '',
    tiktok: '',
    linkedin: '',
  },
];
